package token

type TokenType int8

const (
	UNKNOWN TokenType = iota

	FUNC
	KEYWORD
	BOOL
	IDENT

	// symbols
	SEMICOLON
	COLON
	EQUAL
	SYMBOL

	// structure
	PREPROCESSOR
	CBLOCK
	BRACE_LEFT
	BRACE_RIGHT
	CURLY_LEFT
	CURLY_RIGHT
	BRACKET_LEFT
	BRACKET_RIGHT

	// constants
	NUMBER
	STRING

	EOF
)

var LOOKUP = map[TokenType]string{
	UNKNOWN:       "UNKNOWN",
	SYMBOL:        "SYMBOL",
	PREPROCESSOR:  "PREPROCESSOR",
	COLON:         "COLON",
	CBLOCK:        "CBLOCK",
	FUNC:          "FUNC",
	BOOL:          "BOOL",
	SEMICOLON:     "SEMICOLON",
	IDENT:         "IDENT",
	EQUAL:         "EQUAL",
	BRACE_LEFT:    "BRACE_LEFT",
	BRACE_RIGHT:   "BRACE_RIGHT",
	CURLY_LEFT:    "CURLY_LEFT",
	CURLY_RIGHT:   "CURLY_RIGHT",
	BRACKET_LEFT:  "BRACKET_LEFT",
	BRACKET_RIGHT: "BRACKET_RIGHT",
	NUMBER:        "NUMBER",
	STRING:        "STRING",
	EOF:           "EOF",
}
